// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5-GS12aSgq8wliSE822Fa7o7qbty_sqM',
    appId: '1:88061772717:web:e8d37002be971cf4c19724',
    messagingSenderId: '88061772717',
    projectId: 'metta-87b5e',
    authDomain: 'metta-87b5e.firebaseapp.com',
    databaseURL: 'https://metta-87b5e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'metta-87b5e.appspot.com',
    measurementId: 'G-W9WVBL271X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwVsWtQW2JK0GhDRRjVkK_aKTnp_LDMhE',
    appId: '1:88061772717:android:af7d7df8a85c8efec19724',
    messagingSenderId: '88061772717',
    projectId: 'metta-87b5e',
    databaseURL: 'https://metta-87b5e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'metta-87b5e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSnJiIb6TkyMbhs7IVVq5ifa_tVFSNhGM',
    appId: '1:88061772717:ios:3a8048624e257eabc19724',
    messagingSenderId: '88061772717',
    projectId: 'metta-87b5e',
    databaseURL: 'https://metta-87b5e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'metta-87b5e.appspot.com',
    iosClientId: '88061772717-ku69e9mhsqm4j9k1nms7ablskn1auh1h.apps.googleusercontent.com',
    iosBundleId: 'com.example.gdsc1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSnJiIb6TkyMbhs7IVVq5ifa_tVFSNhGM',
    appId: '1:88061772717:ios:3a8048624e257eabc19724',
    messagingSenderId: '88061772717',
    projectId: 'metta-87b5e',
    databaseURL: 'https://metta-87b5e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'metta-87b5e.appspot.com',
    iosClientId: '88061772717-ku69e9mhsqm4j9k1nms7ablskn1auh1h.apps.googleusercontent.com',
    iosBundleId: 'com.example.gdsc1',
  );
}
